### ISSUE TITLE
Add support for Gradle 8.0

### ISSUE THREAD

**Issue by flelli** [mooltiverse/nyx#162]

**Comment by flelli** [comment]
Using Gradle 8.0 as the primary build tool results in an error due to the [Sonar](https://docs.sonarcloud.io/advanced-setup/ci-based-analysis/sonarscanner-for-gradle/) plugin using no longer supported APIs.

Before switching to Gradle 8.0 as the primary build tool we need to wait for the [Sonar](https://docs.sonarcloud.io/advanced-setup/ci-based-analysis/sonarscanner-for-gradle/) plugin to upgrade and support Gradle 8.0 API.
The [latest version](https://plugins.gradle.org/plugin/org.sonarqube) is `3.5.0.2730`.

In detail, the exception looks like:

```
* What went wrong:
'org.gradle.api.provider.Provider org.gradle.api.reporting.Report.getOutputLocation()'

java.lang.NoSuchMethodError: 'org.gradle.api.provider.Provider org.gradle.api.reporting.Report.getOutputLocation()'
	at org.sonarqube.gradle.SonarPropertyComputer.getDestination(SonarPropertyComputer.java:423)
	at org.sonarqube.gradle.SonarPropertyComputer.configureTestReports(SonarPropertyComputer.java:286)
	at org.sonarqube.gradle.SonarPropertyComputer.extractTestProperties(SonarPropertyComputer.java:255)
```

**Comment by flelli** [comment]
Due to the above, Gradle has been downgraded to the previous version `7.6`.

However, Nyx is still tested also against 8.0.

What is left to do is just upgrade the [Sonar](https://docs.sonarcloud.io/advanced-setup/ci-based-analysis/sonarscanner-for-gradle/) plugin (when available) and upgrade the gradle wrapper running:

```
./gradlew wrapper --gradle-version=8.0
```
