### ISSUE TITLE
Timezones in State files are inconsistent between Java and Go

### ISSUE THREAD

**Issue by flelli** [mooltiverse/nyx#170]
The timezone attributes in timestamps have different formats between Java and Go so a State file marhshalled with one cannot be unmarshalled with the other.

See this example about a `releaseScope/commits/#/authorAction/timeStamp` coming from a JSON State file generated with Java:

```json
"timeStamp" : {
   "timeStamp" : 1676540658000,
   "timeZone" : "GMT+01:00"
}
```

While this is the same example when the State is generated by Go:

```json
"timeStamp" : {
   "timeStamp" : 1676540658000,
   "timeZone" : {}
}
```

Timezones in State files generated with Go are not even marshalled, as only a `{}` is saved.

This issue becomes evident when Go needs to unmarshal a State generated with Java or viceversa. This prevents the different implementations of Nyx to be used in combination (see #168 ).

When using the Go version to unmarshal a Java State we get the error:

```
unable to unmarshal content from file '/github/workspace/build/.nyx-state.json': json: cannot unmarshal string into Go struct field TimeStamp.releaseScope.commits.authorAction.timeStamp.timeZone of type time.Location
```

When using the Java version to unmarshal a Go State we get the error:

```
Unable to unmarshal content from file '/home/runner/work/toolbox/toolbox/build/.nyx-state.json'

com.mooltiverse.oss.nyx.io.DataAccessException: Unable to unmarshal content from file '/home/runner/work/toolbox/toolbox/build/.nyx-state.json'
	at com.mooltiverse.oss.nyx.io.FileMapper.load(FileMapper.java:111)
	at com.mooltiverse.oss.nyx.state.State.resume(State.java:166)
	at com.mooltiverse.oss.nyx.Nyx.state(Nyx.java:183)
	at com.mooltiverse.oss.nyx.gradle.CoreTask.nyx(CoreTask.java:143)
	at com.mooltiverse.oss.nyx.gradle.InferTask.infer(InferTask.java:66)
	...
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.util.TimeZone` from Object value (token `JsonToken.START_OBJECT`)
 at [Source: (File); line: 252, column: 25] (through reference chain: com.mooltiverse.oss.nyx.state.State["releaseScope"]->com.mooltiverse.oss.nyx.entities.ReleaseScope["commits"]->java.util.ArrayList[0]->com.mooltiverse.oss.nyx.entities.git.Commit["authorAction"]->com.mooltiverse.oss.nyx.entities.git.Action["timeStamp"]->com.mooltiverse.oss.nyx.entities.git.TimeStamp["timeZone"])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1741)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1515)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1420)
	at com.fasterxml.jackson.databind.DeserializationContext.extractScalarFromObject(DeserializationContext.java:932)
	at com.fasterxml.jackson.databind.deser.std.FromStringDeserializer.deserialize(FromStringDeserializer.java:155)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:542)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:564)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:439)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:542)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:564)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:439)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:542)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:564)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:439)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:355)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3494)
	at com.mooltiverse.oss.nyx.io.FileMapper.load(FileMapper.java:108)
	... 190 more
```

**Comment by flelli** [comment]
The fix is also an improvement as now the timezone offset is stored as a simple integer (negative or positive) representing the offset in minutes from UTC. This is also what Git does.

Previously we used to store the string identifier for the timezone, which was not portable and was error prone.
