### ISSUE TITLE
Error during release artifacts publication

### ISSUE THREAD

**Issue by flelli** [mooltiverse/nyx#205]
[This](https://github.com/mooltiverse/nyx/actions/runs/4850550105/jobs/8648612105) Actions job failed when publishing release artifacts to GitHub Releases.

The release itself is correctly published and most of the artifacts are also correctly uploaded, but some are missing:

- Nyx 2.3.1 Binary for FreeBSD-arm
- Nyx 2.3.1 Binary for Linux-mips
- Nyx 2.3.1 Binary for OpenBSD-arm
- Nyx 2.3.1 Binary for Windows-386
- Nyx 2.3.1 Binary for Windows-arm64

The logs don't give much information but it's easy to guess one of the missing artifacts is the one that caused the error, and the other ones were not published just because they were supposed to be uploaded after that.

The log is:

```
> Task :nyxPublish
Publish release: 2.3.2


FAILURE: Build failed with an exception.

> Task :nyxPublish FAILED
* What went wrong:
Execution failed for task ':nyxPublish'.
> com.mooltiverse.oss.nyx.ReleaseException: com.mooltiverse.oss.nyx.io.TransportException: Unable to retrieve the repository 'mooltiverse/nyx'

* Try:

	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:324)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:317)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:303)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:463)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:[38](https://github.com/mooltiverse/nyx/actions/runs/4850550105/jobs/8648612105#step:10:39)0)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)
Caused by: com.mooltiverse.oss.nyx.ReleaseException: com.mooltiverse.oss.nyx.io.TransportException: Unable to retrieve the repository 'mooltiverse/nyx'
	at com.mooltiverse.oss.nyx.command.Publish.publish(Publish.java:147)
	at com.mooltiverse.oss.nyx.command.Publish.run(Publish.java:208)
	at com.mooltiverse.oss.nyx.Nyx.runCommand(Nyx.java:277)
	at com.mooltiverse.oss.nyx.Nyx.publish(Nyx.java:485)
	at com.mooltiverse.oss.nyx.gradle.PublishTask.publish(PublishTask.java:66)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:125)
	... 113 more
Caused by: com.mooltiverse.oss.nyx.io.TransportException: Unable to retrieve the repository 'mooltiverse/nyx'
	at com.mooltiverse.oss.nyx.services.github.GitHub.getRepository(GitHub.java:263)
	at com.mooltiverse.oss.nyx.services.github.GitHub.publishReleaseAssets(GitHub.java:314)
	at com.mooltiverse.oss.nyx.services.github.GitHub.publishReleaseAssets(GitHub.java:48)
	at com.mooltiverse.oss.nyx.command.Publish.publish(Publish.java:133)
	... 119 more
Caused by: org.kohsuke.github.HttpException: 
	at org.kohsuke.github.GitHubConnectorResponseErrorHandler$1.onError(GitHubConnectorResponseErrorHandler.java:62)
	at org.kohsuke.github.GitHubClient.detectKnownErrors(GitHubClient.java:472)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:434)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:[40](https://github.com/mooltiverse/nyx/actions/runs/4850550105/jobs/8648612105#step:10:41)3)
	at org.kohsuke.github.Requester.fetch(Requester.java:85)
	at org.kohsuke.github.GHRepository.read(GHRepository.java:1[45](https://github.com/mooltiverse/nyx/actions/runs/4850550105/jobs/8648612105#step:10:46))
	at org.kohsuke.github.GitHub.getRepository(GitHub.java:684)
	at com.mooltiverse.oss.nyx.services.github.GitHub.getRepository(GitHub.java:260)
	... 122 more
```

so the original cause is `org.kohsuke.github.HttpException` raised by [GitHub API for Java](https://github-api.kohsuke.org/) and unfortunately it doesn't give any details.

The build scan says the root code that raises the exception is `org.kohsuke.github.GitHubConnectorResponseErrorHandler$1.onError(GitHubConnectorResponseErrorHandler.java:62)`, so based on the method name one may argue the issue is due to a wrong response code returned by GitHub.

The Java code where the error is thrown are:

```java
noteRateLimit(request.rateLimitTarget(), connectorResponse);
detectKnownErrors(connectorResponse, request, handler != null);
```

so it may look like it's a GitHub rate limit issue.

This code always worked but recently the library has been updated to version 1.314.

**Comment by flelli** [comment]
If the issue is about rate limiting just refer to https://github.com/mooltiverse/nyx/issues/206

**Comment by flelli** [comment]
The [next run](https://github.com/mooltiverse/nyx/actions/runs/4871575426/jobs/8695957895) had no code changes but just debug enabled during the Publish step and completed with no errors so the issue appears to be ephemeral.

**Comment by flelli** [comment]
After running a few pipelines with rate limit statistics enabled it seems that the issue is due to GitHub rate limits.
Closing this issue.
